### ISSUE TITLE
[Question] babel-plugin-react-docgen-typescript alternatives ?

### ISSUE THREAD

**Issue by francoismassart** [storybookjs/babel-plugin-react-docgen#116]
Hello,
We were using `babel-plugin-react-docgen-typescript` which uses `babel-plugin-react-docgen`.
But `babel-plugin-react-docgen-typescript` is outdated (sept. 2020) and it doesn't work with the latest major of `babel-plugin-react-docgen`.

I was wondering if anyone is using a different tool/setup/config to make `babel-plugin-react-docgen` work with typescript sources.

Thank you

**Comment by IanVS** [comment]
There is also https://github.com/joshwooding/vite-plugin-react-docgen-typescript, which is what Storybook uses for vite-based projects.

For react-docgen, we also have an internal vite plugin (https://github.com/storybookjs/storybook/blob/463b40d594ca2e3e4c3d7c8abe29883dd86412bf/code/frameworks/react-vite/src/plugins/react-docgen.ts), which uses an alpha version of react-docgen which has pretty good typescript support.

I don't know of any other alternatives for webpack projects, but there might be some out there.  Also feel free to submit pull requests and we can try to get these babel plugins updated.
