### ISSUE TITLE
The issue with forwardRef Component

### ISSUE THREAD

**Issue by xiaoshuangLi** [storybookjs/babel-plugin-react-docgen#76]
Following Component won't have ```__docgenInfo```.Because of the ```isReactForwardRefCall ```  in ```react-docgen``` not recognize ```forwardRef(...)```. We get the ast base on ```(props, ref) => {...}```.The ```actualNameHandler``` can't the right name we need.

```
import React, { forwardRef } from 'react';
import PropTypes from 'prop-types';

const Text = forwardRef((props, ref) => {
  return (
    <div>text</div>
  );
});

Text.defaultProps = {
  onClick: PropTypes.func,
  children: PropTypes.node,
  style: PropTypes.object,
};

export default Text;

```

**Comment by danielduan** [comment]
@xiaoshuangLi you are more than welcome to open a PR to fix the bug and add some test cases. unfortunately, I don't have much bandwidth these days to do much feature work.

**Comment by xiaoshuangLi** [comment]
@danielduan Good news. ```react-docgen``` fix this hours ago. #77

**Comment by xiaoshuangLi** [comment]
@danielduan Good news, ```react-docgen``` fixed it hours ago. reactjs/react-docgen#385
