### ISSUE TITLE
Dependency Version Update (react-docgen)

### ISSUE THREAD

**Issue by ethancrook99** [storybookjs/babel-plugin-react-docgen#91]
What would it take to update the react-docgen dependency to 5.3.0? Related to [this issue](https://github.com/storybookjs/storybook/issues/11883), prop tables are still missing props for components that use optional chaining. I tried to update it myself, but I found that all the tests started to fail when I updated to 5.3.0 and I couldn't identify what change made that happen.

**Comment by shilman** [comment]
The dependency is:

> react-docgen": "^5.0.0"

So I think 5.3.0 matches that version spec and there are no changes required in the library, only in your project. No?

**Comment by idbartosz** [comment]
I think it still requires an update on your end

https://github.com/storybookjs/babel-plugin-react-docgen/blob/c02946ed5309f0bcc2df67ac2fdabfbcbc323803/yarn.lock#L3580-L3583

**Comment by shilman** [comment]
@idbartosz I don't think the lock file has any bearing on what gets installed when you add this package, only when you develop this package. Correct me if I'm wrong.

@ethancrook99 thanks for the PR! I'll take a look now!

**Comment by mpcarolin** [comment]
We also encountered this issue and would appreciate a fix (it looks like @ethancrook99 's PR handles that). 

A temporary workaround for us is to use this resolution in our application's `package.json`:

```js
  "resolutions": {
    "ast-types": "^0.14.0"
  },
```

**Comment by IanVS** [comment]
It looks like this issue can be closed, feel free to speak up if you think there's still something to do here.
